### ISSUE TITLE
Can't see the Screen Light

### ISSUE THREAD

**Issue by pocketfpv** [googlevr/media-app-template#1] opened 2017-06-23 06:52 UTC
I build and play the unitypackage, everything is ok but the Screen Light .
I can see Screen Light in unity preview viewport .
 My device don't support daydream

**Comment by dsternfeld7** [comment] 2017-10-02 22:46
What version of Unity are you using? What specifically is the unsupported device?

The issue is likely related to the file Floor.shader used to render the light on the floor, and not the light estimation itself.

**Comment by dsternfeld7** [comment] 2017-10-20 17:04
Closing this issue. If you are still having this problem please feel free to open a new issue.

Thanks,

Dan

**Closed as completed by dsternfeld7** 2017-10-20 17:04 UTC
